version: "3.8"

services:
  es-ojt-api-cal:
    container_name: es-ojt-api-cal
    build:
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Seoul
    env_file:
      - .env
    volumes:
      - ./app:/es-ojt-api/app
      - ./gunicorn.config.py:/es-ojt-api/gunicorn.config.py:ro
      - ./asgi.py:/es-ojt-api/asgi.py:ro
      - /mnt/disks/data/qa42/esojt/api/cal/log:/es-ojt-api/log
    command: gunicorn -n es-ojt-api-cal -c gunicorn.config.py
    network_mode: host
