version: "3.8"
services:
  es-ojt-api:
    container_name: es-ojt-api
    build:
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Seoul
    env_file:
      - es-ojt-api.env
    volumes:
      - ./app:/es-ojt-api/app
      - ./gunicorn.config.py:/es-ojt/gunicorn.config.py:ro
    ports:
      - "8000:8000"
    command: gunicorn -n es-ojt -c gunicorn.config.py
