version: "3.8"

networks:
  elastic:
    driver: bridge

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    environment:
      node.name: es01
      cluster.name: es-docker-cluster
      discovery.type: single-node
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      ELASTIC_PASSWORD: ${ES_PASSWORD}
    volumes:
      - ./elasticsearch/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: "curl -s http://elasticsearch:9200 >/dev/null || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    environment:
      elasticsearch.hosts: "http://elasticsearch:9200"
      elasticsearch.username: kibana_system
      elasticsearch.password: ${ES_PASSWORD}
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy

  es-ojt-api:
    container_name: es-ojt-api
    build:
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Seoul
    env_file:
      - es-ojt-api.env
    volumes:
      - ./app:/es-ojt-api/app
      - ./log:/es-ojt-api/log
      - ./gunicorn.config.py:/es-ojt-api/gunicorn.config.py:ro
    ports:
      - "8000:8000"
    command: gunicorn -n es-ojt-api -c gunicorn.config.py
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
