version: "3.8"

networks:
  outside:
    name: es-ojt-elasticsearch_elastic
    external: true

services:
  es-ojt-api-cal:
    container_name: es-ojt-api-cal
    build:
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Seoul
    env_file:
      - es-ojt-api.env
    volumes:
      - ./app:/es-ojt-api/app
      - ./log:/es-ojt-api/log
      - ./gunicorn.config.py:/es-ojt-api/gunicorn.config.py:ro
    ports:
      - "14285:8000"
    command: gunicorn -n es-ojt-api-cal -c gunicorn.config.py
    networks:
      - outside
